### ISSUE TITLE
Override markup type when HTML panel embedded inside Jade panel

### ISSUE THREAD

**Issue by wtfiwtz** [fortsoft/wicket-jade#1]
Love this Jade panel... looks very nice.

I came across an issue when embedding HTML panels within Jade panels.

You must override the markup type (which is derived from the parent container).

``` java
    @Override
    public MarkupType getMarkupType() {
        return MarkupType.HTML_MARKUP_TYPE;
    }
```

Cheers,

Nigel

**Comment by decebals** [comment]
Hi Nigel

Thank you very much for your nice words. I am happy to help you. 
I fixed this issue. I can release a new version if it's ok for you.

Best regards,
Decebal

**Comment by wtfiwtz** [comment]
Thanks @decebals for turning this around quickly... if its not too much trouble to release a new version, that would be great. If not, I can build it manually from cloning the Github repo.

**Comment by decebals** [comment]
The new version (0.2) is available on maven central repository. Please close this issue if the new version resolves your problem.

**Comment by wtfiwtz** [comment]
Cheers @decebals, looks like its working perfectly fine now. Thanks for your assistance and the quick turnaround!
